version: "3.9"
services:

  ocrd-monitor:
    build:
      context: .
      # args:
      #   VCS_REF: ...
      #   BUILD_DATE: ...

    image: ${MONITOR_IMAGE}

    hostname: ${MONITOR_HOST}

    ports:
      - ${MONITOR_PORT_WEB}:8080
      - ${MONITOR_PORT_GTK}:8085

    volumes:
      - ${MONITOR_DATA}:/data
